import type { Product, User, Order, Review } from "./types"


export const products: Product[] = [
  {
    id: "1",
    title: "Premium Wireless Headphones",
    subtitle: "Studio Quality Sound",
    description:
      "Experience crystal-clear audio with our premium wireless headphones featuring active noise cancellation, 30-hour battery life, and premium comfort padding.",
    price: 299.99,
    originalPrice: 399.99,
    category: "Electronics",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    availability: "in-stock",
    rating: 4.8,
    reviewCount: 124,
    tags: ["wireless", "noise-cancelling", "premium"],
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T15:30:00Z",
  },
  {
    id: "2",
    title: "Smart Fitness Watch",
    subtitle: "Track Your Health",
    description:
      "Monitor your health and fitness with this advanced smartwatch featuring heart rate monitoring, GPS tracking, and 7-day battery life.",
    price: 199.99,
    category: "Electronics",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    availability: "in-stock",
    rating: 4.6,
    reviewCount: 89,
    tags: ["fitness", "smartwatch", "health"],
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-01-18T12:00:00Z",
  },
  {
    id: "3",
    title: "Organic Cotton T-Shirt",
    subtitle: "Sustainable Fashion",
    description:
      "Comfortable and eco-friendly t-shirt made from 100% organic cotton. Perfect for everyday wear with a relaxed fit.",
    price: 29.99,
    category: "Clothing",
    images: ["/placeholder.svg?height=400&width=400"],
    availability: "in-stock",
    rating: 4.4,
    reviewCount: 56,
    tags: ["organic", "cotton", "sustainable"],
    createdAt: "2024-01-12T14:00:00Z",
    updatedAt: "2024-01-19T09:15:00Z",
  },
  {
    id: "4",
    title: "Professional Camera Lens",
    subtitle: "85mm f/1.4 Portrait Lens",
    description:
      "Professional-grade portrait lens with exceptional bokeh and sharpness. Perfect for portrait photography and professional shoots.",
    price: 899.99,
    category: "Electronics",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    availability: "limited",
    rating: 4.9,
    reviewCount: 34,
    tags: ["camera", "lens", "professional"],
    createdAt: "2024-01-08T16:00:00Z",
    updatedAt: "2024-01-22T11:45:00Z",
  },
  {
    id: "5",
    title: "Minimalist Desk Lamp",
    subtitle: "Modern LED Design",
    description:
      "Sleek and modern LED desk lamp with adjustable brightness and color temperature. Perfect for any workspace.",
    price: 79.99,
    category: "Home & Garden",
    images: ["/placeholder.svg?height=400&width=400"],
    availability: "in-stock",
    rating: 4.3,
    reviewCount: 78,
    tags: ["led", "desk", "modern"],
    createdAt: "2024-01-14T12:30:00Z",
    updatedAt: "2024-01-21T16:20:00Z",
  },
  {
    id: "6",
    title: "Luxury Leather Wallet",
    subtitle: "Handcrafted Italian Leather",
    description:
      "Premium handcrafted wallet made from genuine Italian leather. Features multiple card slots and a sleek design.",
    price: 149.99,
    category: "Clothing",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    availability: "in-stock",
    rating: 4.7,
    reviewCount: 92,
    tags: ["leather", "luxury", "handcrafted"],
    createdAt: "2024-01-11T09:00:00Z",
    updatedAt: "2024-01-20T14:10:00Z",
  },
]

export const users: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    role: "customer",
    status: "active",
    createdAt: "2024-01-01T00:00:00Z",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    role: "admin",
    status: "active",
    createdAt: "2024-01-02T00:00:00Z",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "3",
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    role: "customer",
    status: "inactive",
    createdAt: "2024-01-03T00:00:00Z",
  },
]

export const orders: Order[] = [
  {
    id: "ORD-001",
    customerId: "1",
    customerName: "John Doe",
    customerEmail: "john.doe@example.com",
    items: [
      {
        productId: "1",
        productTitle: "Premium Wireless Headphones",
        quantity: 1,
        price: 299.99,
        image: "/placeholder.svg?height=60&width=60",
      },
    ],
    total: 299.99,
    status: "delivered",
    createdAt: "2024-01-15T10:00:00Z",
    shippingAddress: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
    },
  },
  {
    id: "ORD-002",
    customerId: "3",
    customerName: "Bob Johnson",
    customerEmail: "bob.johnson@example.com",
    items: [
      {
        productId: "2",
        productTitle: "Smart Fitness Watch",
        quantity: 1,
        price: 199.99,
        image: "/placeholder.svg?height=60&width=60",
      },
      {
        productId: "3",
        productTitle: "Organic Cotton T-Shirt",
        quantity: 2,
        price: 29.99,
        image: "/placeholder.svg?height=60&width=60",
      },
    ],
    total: 259.97,
    status: "shipped",
    createdAt: "2024-01-18T14:30:00Z",
    shippingAddress: {
      street: "456 Oak Ave",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90210",
      country: "USA",
    },
  },
]

export const reviews: Review[] = [
  {
    id: "1",
    productId: "1",
    userId: "1",
    userName: "John Doe",
    rating: 5,
    comment: "Amazing sound quality and comfort. Highly recommended!",
    createdAt: "2024-01-20T15:00:00Z",
  },
  {
    id: "2",
    productId: "1",
    userId: "3",
    userName: "Bob Johnson",
    rating: 4,
    comment: "Great headphones, but a bit pricey. Worth it for the quality though.",
    createdAt: "2024-01-22T09:30:00Z",
  },
]

export const categories = [
  "All",
  "Electronics",
  "Clothing",
  "Home & Garden",
  "Sports",
  "Books",
  "Beauty",
]
